---
title: "02 Mandy"
author: "Mandy"
date: "2015年10月7日"
output: html_document
---

#Section 4.1.1 Exercise 1(a)
Fibonacci <- numeric(12)
Fibonacci[1] <- Fibonacci[2] <- 2
for (i in 3:12) Fibonacci[i] <- Fibonacci[i - 2] + Fibonacci[i - 1]

#Section 4.1.1 Exercise 1(b)
Fibonacci <- numeric(12)
Fibonacci[1] <- 3
Fibonacci[2] <- 2
for (i in 3:12) Fibonacci[i] <- Fibonacci[i - 2] + Fibonacci[i - 1]

#Section 4.1.1 Exercise 1(c)
Fibonacci <- numeric(12)
Fibonacci[1] <- Fibonacci[2] <- 1
for (i in 3:12) Fibonacci[i] <- -Fibonacci[i - 2] + Fibonacci[i - 1]

#Section 4.1.1 Exercise 1(d)
Fibonacci <- numeric(12)
Fibonacci[1] <- Fibonacci[2] <- Fibonacci[3] <-1
for (i in 4:12) Fibonacci[i] <- Fibonacci[i - 3] + Fibonacci[i - 2] + Fibonacci[i - 1]

#Section 4.1.1 Exercise 2(a)
Fibonacci <- numeric(30)
Fibonacci[1] <- Fibonacci[2] <- 1
ratio <- numeric(29)
ratio [1] <- Fibonacci[2] / Fibonacci[1]
for (i in 3:30) {
      Fibonacci[i] <- Fibonacci[i - 2] + Fibonacci[i - 1]
      ratio[i] <- Fibonacci[i] / Fibonacci[i-1]
}
ratio
It looks like ratio series is converging

#Section 4.1.1 Exercise 2(b)
j <- (1 + 5^(1/2)) / 2
j

#Section 4.1.1 Exercise 3(a)
answer <- 0
for (j in 1:5) answer <- answer + j

#Section 4.1.1 Exercise 3(b)
answer <- NULL
for (j in 1:5) answer <- c(answer, j)
class(answer)

#Section 4.1.1 Exercise 3(c)
answer <- 0
for (j in 1:5) answer <- c(answer, j)

#Section 4.1.1 Exercise 3(d)
answer <- 1
for (j in 1:5) answer <- answer * j
answer

#Section 4.1.1 Exercise 3(e)
answer <- 3
for (j in 1:15) answer <- c(answer, (7 * answer[j]) %% 31)

#Section 4.1.2 Exercise 2
Eratosthenes <- function(n) {
 #Return all prime numbers up to n 
    if(n>=2){
      sieve <- seq(2, n)
      primes <- c()
      for (i in seq(2, n)) {
        if (any(sieve == i)) {
          primes <- c(primes, i)
          sieve <- c(sieve[(sieve %% i) != 0], i)
        }
      }
      return(primes)
    } else {
        stop("Input value of n should be at least 2.")
}
  #
  
#Section 4.1.2 Exercise 4
f <- function (P, n){
  if (n >= 3) {
    i <- 0.05
  } 
  else {
    i <- 0.04
  }
  I <- P * ((1 + i) ^ n - 1)
}
f(1, 5)

